name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:            
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install SonarCloud scanner
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet tool install --global dotnet-sonarscanner

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore      

    - name: Run tests and generate code coverage
      run: | 
        dotnet sonarscanner begin /k:"fructuoso_trilha-net-api-desafio" /o:fructuoso /d:sonar.token=${{ secrets.GITHUB_TOKEN }} /d:sonar.cs.opencover.reportsPaths=coverage/coverage.opencover.xml /d:sonar.log.level=TRACE
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=../coverage/ /p:CoverletOutputFormat=\"opencover\"
        dotnet sonarscanner end /d:sonar.token=${{ secrets.SONAR_TOKEN }}