name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:            
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore      

    - name: Run tests and generate code coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=../coverage/ /p:CoverletOutputFormat=\"cobertura,opencover\"

    - name: Report code coverage to SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=fructuoso
          -Dsonar.projectKey=fructuoso_trilha-net-api-desafio3

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./
        args: >
          -Dsonar.organization=fructuoso
          -Dsonar.projectKey=fructuoso_trilha-net-api-desafio3
          -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
          -Dsonar.sources=src/
          -Dsonar.test.exclusions=tests/**
          -Dsonar.tests=tests/
          -Dsonar.verbose=true
          -Dsonar.log.level=TRACE