name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:            
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore      

    - name: Run tests and generate code coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage"

    - name: Report code coverage to SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=fructuoso
          -Dsonar.projectKey=fructuoso_trilha-net-api-desafio
          -Dsonar.coverageReportPaths=**/coverage.cobertura.xml