name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:            
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install SonarCloud scanner
      run: |
        dotnet tool install --global dotnet-coverage

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore      

    - name: Run tests and generate code coverage
      run: | 
        dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage.xml'

    - name: Test
      run: |
        echo $(pwd)
        ls
        cat coverage.xml

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=fructuoso
          -Dsonar.projectKey=fructuoso_trilha-net-api-desafio3
          -Dsonar.cs.vscoveragexml.reportsPaths=coverage.xml
          -Dsonar.sources=src
          -Dsonar.verbose=true
          -Dsonar.log.level=TRACE